sudo: required
services:
  - docker

before-install:
  - docker build -t danilarff86/leetcode_solutions -f Dockerfile .

script:
  - docker run danilarff86/leetcode_solutions ./build/solutions/solutions
